FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_VERSION=2.1.1 \
    POETRY_NO_INTERACTION=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl libpq-dev && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

WORKDIR /app

COPY pyproject.toml poetry.lock* ./
COPY lib ./lib

# Instala deps en el sistema (sin venv) para que el bind mount no las tape
RUN poetry config virtualenvs.create false && \
    poetry install --no-root

COPY src ./src
COPY osiris ./osiris
COPY conf ./conf

EXPOSE 8000
CMD ["poetry","run","uvicorn","osiris.main:app","--host","0.0.0.0","--port","8000","--reload"]
