"""

Revision ID: 06ee39e487b6
Revises: 6500f1c98911
Create Date: 2025-11-29 17:46:43.830423

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '06ee39e487b6'
down_revision: Union[str, None] = '6500f1c98911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
