"""add valor field to tipo_producto

Revision ID: 0cd6bb724d55
Revises: 5c4fcff72efa
Create Date: 2025-11-28 17:42:56.482310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cd6bb724d55'
down_revision: Union[str, None] = '5c4fcff72efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_producto', 'tipo',
               existing_type=postgresql.ENUM('BIEN', 'SERVICIO', name='tipoproducto'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tbl_producto', 'pvp',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.add_column('tbl_tipo_producto', sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_tipo_producto', 'valor')
    op.alter_column('tbl_producto', 'pvp',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('tbl_producto', 'tipo',
               existing_type=postgresql.ENUM('BIEN', 'SERVICIO', name='tipoproducto'),
               server_default=sa.text("'BIEN'::tipoproducto"),
               existing_nullable=False)
    # ### end Alembic commands ###
