"""add cantidad to producto

Revision ID: 15b92ec527c1
Revises: 20f3d9f4a008
Create Date: 2025-12-02 11:41:21.786366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b92ec527c1'
down_revision: Union[str, None] = '20f3d9f4a008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_producto', sa.Column('cantidad', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_producto', 'cantidad')
    # ### end Alembic commands ###
