"""añadir tablas modulo y rol_modulo_permiso para sistema de permisos

Revision ID: 219b76343e08
Revises: fc65b5f4ec8d
Create Date: 2025-12-03 04:02:53.687625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '219b76343e08'
down_revision: Union[str, None] = 'fc65b5f4ec8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_modulo',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('icono', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_modulo_activo'), 'tbl_modulo', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_modulo_codigo'), 'tbl_modulo', ['codigo'], unique=True)
    op.create_index(op.f('ix_tbl_modulo_id'), 'tbl_modulo', ['id'], unique=False)
    op.create_table('roles_modulos_permisos',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('modulo_id', sa.Uuid(), nullable=False),
    sa.Column('puede_leer', sa.Boolean(), nullable=False),
    sa.Column('puede_crear', sa.Boolean(), nullable=False),
    sa.Column('puede_actualizar', sa.Boolean(), nullable=False),
    sa.Column('puede_eliminar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['tbl_modulo.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['tbl_rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'modulo_id', name='uq_rol_modulo')
    )
    op.create_index(op.f('ix_roles_modulos_permisos_activo'), 'roles_modulos_permisos', ['activo'], unique=False)
    op.create_index(op.f('ix_roles_modulos_permisos_id'), 'roles_modulos_permisos', ['id'], unique=False)
    op.create_index(op.f('ix_roles_modulos_permisos_modulo_id'), 'roles_modulos_permisos', ['modulo_id'], unique=False)
    op.create_index(op.f('ix_roles_modulos_permisos_rol_id'), 'roles_modulos_permisos', ['rol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_modulos_permisos_rol_id'), table_name='roles_modulos_permisos')
    op.drop_index(op.f('ix_roles_modulos_permisos_modulo_id'), table_name='roles_modulos_permisos')
    op.drop_index(op.f('ix_roles_modulos_permisos_id'), table_name='roles_modulos_permisos')
    op.drop_index(op.f('ix_roles_modulos_permisos_activo'), table_name='roles_modulos_permisos')
    op.drop_table('roles_modulos_permisos')
    op.drop_index(op.f('ix_tbl_modulo_id'), table_name='tbl_modulo')
    op.drop_index(op.f('ix_tbl_modulo_codigo'), table_name='tbl_modulo')
    op.drop_index(op.f('ix_tbl_modulo_activo'), table_name='tbl_modulo')
    op.drop_table('tbl_modulo')
    # ### end Alembic commands ###
