"""crear_tabla_bodega_con_import

Revision ID: 32e17e50d302
Revises: bccdb08e7f6b
Create Date: 2025-12-02 13:36:16.138284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32e17e50d302'
down_revision: Union[str, None] = 'bccdb08e7f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_bodega',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_bodega', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre_bodega', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['tbl_empresa.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['tbl_sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_bodega_activo'), 'tbl_bodega', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_bodega_codigo_bodega'), 'tbl_bodega', ['codigo_bodega'], unique=False)
    op.create_index(op.f('ix_tbl_bodega_empresa_id'), 'tbl_bodega', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_tbl_bodega_id'), 'tbl_bodega', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_bodega_sucursal_id'), 'tbl_bodega', ['sucursal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_bodega_sucursal_id'), table_name='tbl_bodega')
    op.drop_index(op.f('ix_tbl_bodega_id'), table_name='tbl_bodega')
    op.drop_index(op.f('ix_tbl_bodega_empresa_id'), table_name='tbl_bodega')
    op.drop_index(op.f('ix_tbl_bodega_codigo_bodega'), table_name='tbl_bodega')
    op.drop_index(op.f('ix_tbl_bodega_activo'), table_name='tbl_bodega')
    op.drop_table('tbl_bodega')
    # ### end Alembic commands ###
