"""create_tbl_casa_comercial

Revision ID: 34c363629f4f
Revises: c1f2d3e4b5a6
Create Date: 2025-11-27 15:43:56.846221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34c363629f4f'
down_revision: Union[str, None] = 'c1f2d3e4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_casa_comercial',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_casa_comercial_activo'), 'tbl_casa_comercial', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_casa_comercial_id'), 'tbl_casa_comercial', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_casa_comercial_nombre'), 'tbl_casa_comercial', ['nombre'], unique=True)
    op.create_index(op.f('ix_tbl_categoria_es_padre'), 'tbl_categoria', ['es_padre'], unique=False)
    op.create_index(op.f('ix_tbl_categoria_nombre'), 'tbl_categoria', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_categoria_nombre'), table_name='tbl_categoria')
    op.drop_index(op.f('ix_tbl_categoria_es_padre'), table_name='tbl_categoria')
    op.drop_index(op.f('ix_tbl_casa_comercial_nombre'), table_name='tbl_casa_comercial')
    op.drop_index(op.f('ix_tbl_casa_comercial_id'), table_name='tbl_casa_comercial')
    op.drop_index(op.f('ix_tbl_casa_comercial_activo'), table_name='tbl_casa_comercial')
    op.drop_table('tbl_casa_comercial')
    # ### end Alembic commands ###
