"""create tbl_categoria_atributo

Revision ID: 4d0f0ae69511
Revises: f0749c01d405
Create Date: 2025-12-02 12:21:07.821106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d0f0ae69511'
down_revision: Union[str, None] = 'f0749c01d405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_categoria_atributo',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('atributo_id', sa.Uuid(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['atributo_id'], ['tbl_atributo.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['tbl_categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_categoria_atributo_activo'), 'tbl_categoria_atributo', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_categoria_atributo_atributo_id'), 'tbl_categoria_atributo', ['atributo_id'], unique=False)
    op.create_index(op.f('ix_tbl_categoria_atributo_categoria_id'), 'tbl_categoria_atributo', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_tbl_categoria_atributo_id'), 'tbl_categoria_atributo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_categoria_atributo_id'), table_name='tbl_categoria_atributo')
    op.drop_index(op.f('ix_tbl_categoria_atributo_categoria_id'), table_name='tbl_categoria_atributo')
    op.drop_index(op.f('ix_tbl_categoria_atributo_atributo_id'), table_name='tbl_categoria_atributo')
    op.drop_index(op.f('ix_tbl_categoria_atributo_activo'), table_name='tbl_categoria_atributo')
    op.drop_table('tbl_categoria_atributo')
    # ### end Alembic commands ###
