"""add_impuestos_catalogo_and_producto_impuesto

Revision ID: 5c4fcff72efa
Revises: ad96a08021df
Create Date: 2025-11-28 13:06:31.268165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c4fcff72efa'
down_revision: Union[str, None] = 'ad96a08021df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aux_impuesto_catalogo',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_impuesto', sa.Enum('IVA', 'ICE', name='tipoimpuesto'), nullable=False),
    sa.Column('codigo_sri', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('aplica_a', sa.Enum('BIEN', 'SERVICIO', 'AMBOS', name='aplicaa'), nullable=False),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('clasificacion_iva', sa.Enum('GRAVADO', 'EXENTO', 'NO_OBJETO', 'DIFERENCIADO', 'OTRO', name='clasificacioniva'), nullable=True),
    sa.Column('tarifa_ad_valorem', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tarifa_especifica', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('modo_calculo_ice', sa.Enum('AD_VALOREM', 'ESPECIFICO', 'MIXTO', name='modocalculoice'), nullable=True),
    sa.Column('unidad_base', sa.Enum('UNIDAD', 'LITRO', 'KILO', 'MIL_UNIDADES', 'OTRO', name='unidadbase'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_impuesto_catalogo_activo'), 'aux_impuesto_catalogo', ['activo'], unique=False)
    op.create_index(op.f('ix_aux_impuesto_catalogo_codigo_sri'), 'aux_impuesto_catalogo', ['codigo_sri'], unique=True)
    op.create_index(op.f('ix_aux_impuesto_catalogo_id'), 'aux_impuesto_catalogo', ['id'], unique=False)
    op.create_index(op.f('ix_aux_impuesto_catalogo_tipo_impuesto'), 'aux_impuesto_catalogo', ['tipo_impuesto'], unique=False)
    op.create_index(op.f('ix_aux_impuesto_catalogo_vigente_desde'), 'aux_impuesto_catalogo', ['vigente_desde'], unique=False)
    op.create_index(op.f('ix_aux_impuesto_catalogo_vigente_hasta'), 'aux_impuesto_catalogo', ['vigente_hasta'], unique=False)
    op.create_table('tbl_producto_impuesto',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('impuesto_catalogo_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['impuesto_catalogo_id'], ['aux_impuesto_catalogo.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['tbl_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_producto_impuesto_activo'), 'tbl_producto_impuesto', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_producto_impuesto_id'), 'tbl_producto_impuesto', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_impuesto_impuesto_catalogo_id'), 'tbl_producto_impuesto', ['impuesto_catalogo_id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_impuesto_producto_id'), 'tbl_producto_impuesto', ['producto_id'], unique=False)

    # Crear tipo ENUM antes de agregar la columna
    tipo_producto_enum = sa.Enum('BIEN', 'SERVICIO', name='tipoproducto')
    tipo_producto_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('tbl_producto', sa.Column('tipo', tipo_producto_enum, nullable=False, server_default='BIEN'))
    op.add_column('tbl_producto', sa.Column('pvp', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_producto', 'pvp')
    op.drop_column('tbl_producto', 'tipo')

    # Eliminar tipo ENUM después de quitar la columna
    tipo_producto_enum = sa.Enum('BIEN', 'SERVICIO', name='tipoproducto')
    tipo_producto_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_tbl_producto_impuesto_producto_id'), table_name='tbl_producto_impuesto')
    op.drop_index(op.f('ix_tbl_producto_impuesto_impuesto_catalogo_id'), table_name='tbl_producto_impuesto')
    op.drop_index(op.f('ix_tbl_producto_impuesto_id'), table_name='tbl_producto_impuesto')
    op.drop_index(op.f('ix_tbl_producto_impuesto_activo'), table_name='tbl_producto_impuesto')
    op.drop_table('tbl_producto_impuesto')
    op.drop_index(op.f('ix_aux_impuesto_catalogo_vigente_hasta'), table_name='aux_impuesto_catalogo')
    op.drop_index(op.f('ix_aux_impuesto_catalogo_vigente_desde'), table_name='aux_impuesto_catalogo')
    op.drop_index(op.f('ix_aux_impuesto_catalogo_tipo_impuesto'), table_name='aux_impuesto_catalogo')
    op.drop_index(op.f('ix_aux_impuesto_catalogo_id'), table_name='aux_impuesto_catalogo')
    op.drop_index(op.f('ix_aux_impuesto_catalogo_codigo_sri'), table_name='aux_impuesto_catalogo')
    op.drop_index(op.f('ix_aux_impuesto_catalogo_activo'), table_name='aux_impuesto_catalogo')
    op.drop_table('aux_impuesto_catalogo')
    # ### end Alembic commands ###
