"""crear tabla producto_bodega

Revision ID: 62b7917189d0
Revises: d95d08db4e07
Create Date: 2025-12-02 14:42:57.025727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b7917189d0'
down_revision: Union[str, None] = 'd95d08db4e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_producto_bodega',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['tbl_bodega.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['tbl_producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'bodega_id', name='uq_producto_bodega')
    )
    op.create_index(op.f('ix_tbl_producto_bodega_bodega_id'), 'tbl_producto_bodega', ['bodega_id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_bodega_id'), 'tbl_producto_bodega', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_bodega_producto_id'), 'tbl_producto_bodega', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_producto_bodega_producto_id'), table_name='tbl_producto_bodega')
    op.drop_index(op.f('ix_tbl_producto_bodega_id'), table_name='tbl_producto_bodega')
    op.drop_index(op.f('ix_tbl_producto_bodega_bodega_id'), table_name='tbl_producto_bodega')
    op.drop_table('tbl_producto_bodega')
    # ### end Alembic commands ###
