"""create producto/atributo/tipo_producto and bridges

Revision ID: ad96a08021df
Revises: 483805449635
Create Date: 2025-11-27 18:37:00.468215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad96a08021df'
down_revision: Union[str, None] = '483805449635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_atributo',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('tipo_dato', sa.Enum('STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'DATE', name='tipodato'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_atributo_activo'), 'tbl_atributo', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_atributo_id'), 'tbl_atributo', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_atributo_nombre'), 'tbl_atributo', ['nombre'], unique=True)
    op.create_table('tbl_producto',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('casa_comercial_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['casa_comercial_id'], ['tbl_casa_comercial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_producto_activo'), 'tbl_producto', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_producto_id'), 'tbl_producto', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_nombre'), 'tbl_producto', ['nombre'], unique=True)
    op.create_table('tbl_producto_categoria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['tbl_categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['tbl_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_producto_categoria_categoria_id'), 'tbl_producto_categoria', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_categoria_id'), 'tbl_producto_categoria', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_categoria_producto_id'), 'tbl_producto_categoria', ['producto_id'], unique=False)
    op.create_table('tbl_producto_proveedor_persona',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('proveedor_persona_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['tbl_producto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_persona_id'], ['tbl_proveedor_persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_producto_proveedor_persona_id'), 'tbl_producto_proveedor_persona', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_proveedor_persona_producto_id'), 'tbl_producto_proveedor_persona', ['producto_id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_proveedor_persona_proveedor_persona_id'), 'tbl_producto_proveedor_persona', ['proveedor_persona_id'], unique=False)
    op.create_table('tbl_producto_proveedor_sociedad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('proveedor_sociedad_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['tbl_producto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_sociedad_id'], ['tbl_proveedor_sociedad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_producto_proveedor_sociedad_id'), 'tbl_producto_proveedor_sociedad', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_proveedor_sociedad_producto_id'), 'tbl_producto_proveedor_sociedad', ['producto_id'], unique=False)
    op.create_index(op.f('ix_tbl_producto_proveedor_sociedad_proveedor_sociedad_id'), 'tbl_producto_proveedor_sociedad', ['proveedor_sociedad_id'], unique=False)
    op.create_table('tbl_tipo_producto',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('atributo_id', sa.Uuid(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['atributo_id'], ['tbl_atributo.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['tbl_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_tipo_producto_activo'), 'tbl_tipo_producto', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_tipo_producto_atributo_id'), 'tbl_tipo_producto', ['atributo_id'], unique=False)
    op.create_index(op.f('ix_tbl_tipo_producto_id'), 'tbl_tipo_producto', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_tipo_producto_producto_id'), 'tbl_tipo_producto', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_tipo_producto_producto_id'), table_name='tbl_tipo_producto')
    op.drop_index(op.f('ix_tbl_tipo_producto_id'), table_name='tbl_tipo_producto')
    op.drop_index(op.f('ix_tbl_tipo_producto_atributo_id'), table_name='tbl_tipo_producto')
    op.drop_index(op.f('ix_tbl_tipo_producto_activo'), table_name='tbl_tipo_producto')
    op.drop_table('tbl_tipo_producto')
    op.drop_index(op.f('ix_tbl_producto_proveedor_sociedad_proveedor_sociedad_id'), table_name='tbl_producto_proveedor_sociedad')
    op.drop_index(op.f('ix_tbl_producto_proveedor_sociedad_producto_id'), table_name='tbl_producto_proveedor_sociedad')
    op.drop_index(op.f('ix_tbl_producto_proveedor_sociedad_id'), table_name='tbl_producto_proveedor_sociedad')
    op.drop_table('tbl_producto_proveedor_sociedad')
    op.drop_index(op.f('ix_tbl_producto_proveedor_persona_proveedor_persona_id'), table_name='tbl_producto_proveedor_persona')
    op.drop_index(op.f('ix_tbl_producto_proveedor_persona_producto_id'), table_name='tbl_producto_proveedor_persona')
    op.drop_index(op.f('ix_tbl_producto_proveedor_persona_id'), table_name='tbl_producto_proveedor_persona')
    op.drop_table('tbl_producto_proveedor_persona')
    op.drop_index(op.f('ix_tbl_producto_categoria_producto_id'), table_name='tbl_producto_categoria')
    op.drop_index(op.f('ix_tbl_producto_categoria_id'), table_name='tbl_producto_categoria')
    op.drop_index(op.f('ix_tbl_producto_categoria_categoria_id'), table_name='tbl_producto_categoria')
    op.drop_table('tbl_producto_categoria')
    op.drop_index(op.f('ix_tbl_producto_nombre'), table_name='tbl_producto')
    op.drop_index(op.f('ix_tbl_producto_id'), table_name='tbl_producto')
    op.drop_index(op.f('ix_tbl_producto_activo'), table_name='tbl_producto')
    op.drop_table('tbl_producto')
    op.drop_index(op.f('ix_tbl_atributo_nombre'), table_name='tbl_atributo')
    op.drop_index(op.f('ix_tbl_atributo_id'), table_name='tbl_atributo')
    op.drop_index(op.f('ix_tbl_atributo_activo'), table_name='tbl_atributo')
    op.drop_table('tbl_atributo')
    # ### end Alembic commands ###
