"""crear_tabla_bodega

Revision ID: bccdb08e7f6b
Revises: 9f1b2c7a1de4
Create Date: 2025-12-02 13:35:36.926777

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'bccdb08e7f6b'
down_revision: Union[str, None] = '9f1b2c7a1de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
