"""añadir campo logo a tabla empresa

Revision ID: d95d08db4e07
Revises: 32e17e50d302
Create Date: 2025-12-02 14:17:08.698082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd95d08db4e07'
down_revision: Union[str, None] = '32e17e50d302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_empresa', sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_empresa', 'logo')
    # ### end Alembic commands ###
