"""add categoria_atributo mapping

Revision ID: f0749c01d405
Revises: 15b92ec527c1
Create Date: 2025-12-02 12:20:05.041540

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f0749c01d405'
down_revision: Union[str, None] = '15b92ec527c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
