"""initial schema (sqlmodel)

Revision ID: f277a59033e3
Revises: 
Create Date: 2025-11-06 15:01:28.435487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f277a59033e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aux_tipo_contribuyente',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('tbl_persona',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_identificacion', postgresql.ENUM('CEDULA', 'RUC', 'PASAPORTE', name='tipo_identificacion_enum'), nullable=False),
    sa.Column('identificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_persona_activo'), 'tbl_persona', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_persona_apellido'), 'tbl_persona', ['apellido'], unique=False)
    op.create_index(op.f('ix_tbl_persona_id'), 'tbl_persona', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_persona_identificacion'), 'tbl_persona', ['identificacion'], unique=True)
    op.create_index(op.f('ix_tbl_persona_nombre'), 'tbl_persona', ['nombre'], unique=False)
    op.create_table('tbl_rol',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_rol_activo'), 'tbl_rol', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_rol_id'), 'tbl_rol', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_rol_nombre'), 'tbl_rol', ['nombre'], unique=True)
    op.create_table('tbl_tipo_cliente',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.CheckConstraint('descuento >= 0 AND descuento <= 100', name='ck_descuento_rango'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_tipo_cliente_activo'), 'tbl_tipo_cliente', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_tipo_cliente_id'), 'tbl_tipo_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_tipo_cliente_nombre'), 'tbl_tipo_cliente', ['nombre'], unique=True)
    op.create_table('tbl_cliente',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_cliente_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_cliente_id'], ['tbl_tipo_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_cliente_activo'), 'tbl_cliente', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_cliente_id'), 'tbl_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_cliente_persona_id'), 'tbl_cliente', ['persona_id'], unique=True)
    op.create_index(op.f('ix_tbl_cliente_tipo_cliente_id'), 'tbl_cliente', ['tipo_cliente_id'], unique=False)
    op.create_table('tbl_empleado',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_empleado_activo'), 'tbl_empleado', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_empleado_id'), 'tbl_empleado', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_empleado_persona_id'), 'tbl_empleado', ['persona_id'], unique=True)
    op.create_table('tbl_empresa',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nombre_comercial', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ruc', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('direccion_matriz', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('codigo_establecimiento', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('obligado_contabilidad', sa.Boolean(), nullable=False),
    sa.Column('tipo_contribuyente_id', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.ForeignKeyConstraint(['tipo_contribuyente_id'], ['aux_tipo_contribuyente.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_empresa_activo'), 'tbl_empresa', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_empresa_id'), 'tbl_empresa', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_empresa_razon_social'), 'tbl_empresa', ['razon_social'], unique=False)
    op.create_index(op.f('ix_tbl_empresa_ruc'), 'tbl_empresa', ['ruc'], unique=False)
    op.create_table('tbl_proveedor_persona',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_comercial', sa.String(), nullable=True),
    sa.Column('tipo_contribuyente_id', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_contribuyente_id'], ['aux_tipo_contribuyente.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_proveedor_persona_activo'), 'tbl_proveedor_persona', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_proveedor_persona_id'), 'tbl_proveedor_persona', ['id'], unique=False)
    op.create_table('tbl_proveedor_sociedad',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ruc', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_comercial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_contribuyente_id', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('persona_contacto_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_contacto_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_contribuyente_id'], ['aux_tipo_contribuyente.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_tbl_proveedor_sociedad_activo'), 'tbl_proveedor_sociedad', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_proveedor_sociedad_id'), 'tbl_proveedor_sociedad', ['id'], unique=False)
    op.create_table('tbl_usuario',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('requiere_cambio_password', sa.Boolean(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['tbl_rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_index(op.f('ix_tbl_usuario_activo'), 'tbl_usuario', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_usuario_id'), 'tbl_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_usuario_username'), 'tbl_usuario', ['username'], unique=True)
    op.create_table('tbl_sucursal',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['tbl_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_sucursal_activo'), 'tbl_sucursal', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_sucursal_codigo'), 'tbl_sucursal', ['codigo'], unique=False)
    op.create_index(op.f('ix_tbl_sucursal_id'), 'tbl_sucursal', ['id'], unique=False)
    op.create_table('tbl_punto_emision',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('secuencial_actual', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['tbl_empresa.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['tbl_sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'sucursal_id', 'codigo', name='uq_pe_empresa_sucursal_codigo')
    )
    op.create_index(op.f('ix_tbl_punto_emision_activo'), 'tbl_punto_emision', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_punto_emision_id'), 'tbl_punto_emision', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_punto_emision_id'), table_name='tbl_punto_emision')
    op.drop_index(op.f('ix_tbl_punto_emision_activo'), table_name='tbl_punto_emision')
    op.drop_table('tbl_punto_emision')
    op.drop_index(op.f('ix_tbl_sucursal_id'), table_name='tbl_sucursal')
    op.drop_index(op.f('ix_tbl_sucursal_codigo'), table_name='tbl_sucursal')
    op.drop_index(op.f('ix_tbl_sucursal_activo'), table_name='tbl_sucursal')
    op.drop_table('tbl_sucursal')
    op.drop_index(op.f('ix_tbl_usuario_username'), table_name='tbl_usuario')
    op.drop_index(op.f('ix_tbl_usuario_id'), table_name='tbl_usuario')
    op.drop_index(op.f('ix_tbl_usuario_activo'), table_name='tbl_usuario')
    op.drop_table('tbl_usuario')
    op.drop_index(op.f('ix_tbl_proveedor_sociedad_id'), table_name='tbl_proveedor_sociedad')
    op.drop_index(op.f('ix_tbl_proveedor_sociedad_activo'), table_name='tbl_proveedor_sociedad')
    op.drop_table('tbl_proveedor_sociedad')
    op.drop_index(op.f('ix_tbl_proveedor_persona_id'), table_name='tbl_proveedor_persona')
    op.drop_index(op.f('ix_tbl_proveedor_persona_activo'), table_name='tbl_proveedor_persona')
    op.drop_table('tbl_proveedor_persona')
    op.drop_index(op.f('ix_tbl_empresa_ruc'), table_name='tbl_empresa')
    op.drop_index(op.f('ix_tbl_empresa_razon_social'), table_name='tbl_empresa')
    op.drop_index(op.f('ix_tbl_empresa_id'), table_name='tbl_empresa')
    op.drop_index(op.f('ix_tbl_empresa_activo'), table_name='tbl_empresa')
    op.drop_table('tbl_empresa')
    op.drop_index(op.f('ix_tbl_empleado_persona_id'), table_name='tbl_empleado')
    op.drop_index(op.f('ix_tbl_empleado_id'), table_name='tbl_empleado')
    op.drop_index(op.f('ix_tbl_empleado_activo'), table_name='tbl_empleado')
    op.drop_table('tbl_empleado')
    op.drop_index(op.f('ix_tbl_cliente_tipo_cliente_id'), table_name='tbl_cliente')
    op.drop_index(op.f('ix_tbl_cliente_persona_id'), table_name='tbl_cliente')
    op.drop_index(op.f('ix_tbl_cliente_id'), table_name='tbl_cliente')
    op.drop_index(op.f('ix_tbl_cliente_activo'), table_name='tbl_cliente')
    op.drop_table('tbl_cliente')
    op.drop_index(op.f('ix_tbl_tipo_cliente_nombre'), table_name='tbl_tipo_cliente')
    op.drop_index(op.f('ix_tbl_tipo_cliente_id'), table_name='tbl_tipo_cliente')
    op.drop_index(op.f('ix_tbl_tipo_cliente_activo'), table_name='tbl_tipo_cliente')
    op.drop_table('tbl_tipo_cliente')
    op.drop_index(op.f('ix_tbl_rol_nombre'), table_name='tbl_rol')
    op.drop_index(op.f('ix_tbl_rol_id'), table_name='tbl_rol')
    op.drop_index(op.f('ix_tbl_rol_activo'), table_name='tbl_rol')
    op.drop_table('tbl_rol')
    op.drop_index(op.f('ix_tbl_persona_nombre'), table_name='tbl_persona')
    op.drop_index(op.f('ix_tbl_persona_identificacion'), table_name='tbl_persona')
    op.drop_index(op.f('ix_tbl_persona_id'), table_name='tbl_persona')
    op.drop_index(op.f('ix_tbl_persona_apellido'), table_name='tbl_persona')
    op.drop_index(op.f('ix_tbl_persona_activo'), table_name='tbl_persona')
    op.drop_table('tbl_persona')
    op.drop_table('aux_tipo_contribuyente')
    # ### end Alembic commands ###
