"""add empresa_id to empleado

Revision ID: fc65b5f4ec8d
Revises: 8f3a2b1c4d5e
Create Date: 2025-12-02 22:40:13.667616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc65b5f4ec8d'
down_revision: Union[str, None] = '8f3a2b1c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_empleado', sa.Column('empresa_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_tbl_empleado_empresa_id'), 'tbl_empleado', ['empresa_id'], unique=False)
    op.create_foreign_key(None, 'tbl_empleado', 'tbl_empresa', ['empresa_id'], ['id'])
    op.drop_constraint(op.f('uq_producto_bodega'), 'tbl_producto_bodega', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_producto_bodega'), 'tbl_producto_bodega', ['producto_id', 'bodega_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'tbl_empleado', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_empleado_empresa_id'), table_name='tbl_empleado')
    op.drop_column('tbl_empleado', 'empresa_id')
    # ### end Alembic commands ###
